name: test
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get the current date
              run: echo "The time is $(date)"
